sonata_user:
    security_acl: true
    manager_type: orm 
    admin:
        user:
            class:  Application\Sonata\UserBundle\Admin\Entity\UserAdmin
            
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Application\Sonata\UserBundle\Entity\User