sonata_user:
    security_acl: true
    manager_type: orm 
    admin:
        user:
            class:  Application\Sonata\UserBundle\Admin\Entity\UserAdmin
            
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Application\Sonata\UserBundle\Entity\User
    registration:
        confirmation:
            enabled:    true
        form:
            type:  application_sonata_user_registration
            name:  application_sonata_user_registration