sonata_admin:
    title:      Karis CMS Sandbox
    title_logo: ./bundles/prestasonataadminextended/img/logo_title.jpg
    templates:
        # default global templates
        layout:  ::admin_layout.html.twig
    dashboard:
        blocks:
            -
                position: left
                type: sonata.block.service.text
                settings:
                    content: |
                        <h2>Welcome in Karis CMS Sandbox</h2>
                        <p>
                            This is an early release and will be enhanced progressively.
                        </p>
                        <p>
                            Right now features are :
                            <ul>
                                <li>Multiple websites by configuration</li>
                                <li>Multilangue</li>
                                <li>Custom theming</li>
                                <li>Page administration</li>
                            </ul>
                        </p>
                        <p>
                            You can use it freely for your project, open / correct tickets on Github via Pull request.
                        </p>
                        <p>
                            We hope it will help you on your project.
                        </p>
                        <p>
                            Karis CMS is based on Symfony CMF so we would like to thanks people working on it.
                        </p>
                        <p>
                            Karis CMS is sponsored by <a href="agencekarismatik.com/#presentation">Karismatik</a>
                        </p>
            - { position: right, type: sonata.admin.block.admin_list }
        groups:
            sonata_media: ~

            presta_cms_contact:
                label_catalogue: PrestaCMSContactBundle
                items:
                    - presta_cms_contact.admin.contact
                    - presta_cms_contact.admin.message
            sonata.user:
                label: Manage Users 
                items: ~~      
            sonata_manage_email:
                label: Manage Email
                items: ~    
                
            sonata_manage_settings:
                label: Manage Settings
                items: ~         
                   
services:
                   
   rj.email.admin:
      class: Rj\EmailBundle\Admin\EmailTemplateAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: sonata_manage_email, label: Manage Email }
      arguments: [null, Rj\EmailBundle\Entity\EmailTemplate, RjEmailBundle:EmailTemplateAdmin]
      
   sylius.settings.admin:
      class: Application\Sylius\SettingsBundle\Admin\ParameterAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: sonata_manage_settings, label: Manage Settings }
      arguments: [null, Sylius\Bundle\SettingsBundle\Model\Parameter, ApplicationSyliusSettingsBundle:ParameterAdmin]  
